# src/main/resources/application.yml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: admin
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
